tweet_messages/urls.py
from django.conf.urls import url
from . import views
from .forms import LoginForm


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^users/list$', views.users_list, name='user_list'),
    url(r'^users/(?P<id>\d+)/$', views.user_page, name='user_page'),
    url(r'^users/create-message.html/$', views.create_message, name='create_message'),
    url(r'^login/$', 'django.contrib.auth.views.login', 
        {'authentication_form': LoginForm},
        name='login'),

    url(r'^logout/$', 
        'django.contrib.auth.views.logout', 
        {'template_name': 'registration/logout.html'},
        name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^sms/$', views.reply_to_sms_messages),
]

twitter_clone/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('tweet_messages.urls', namespace='tweet_messages')),

]

tweet_messages/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from datetime import datetime
from django.http import HttpResponse
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class TweetMessage(models.Model):
    tweet_messages = models.CharField(max_length=140)
    user = models.ForeignKey(User)
    date = models.DateTimeField('date created', default=datetime.now)
    hashtag = models.CharField(max_length=20, blank=True)

    class Meta:
        ordering = ['-date']


    def __str__(self):
        return self.tweet_messages

class Profile(models.Model):
    user = models.OneToOneField(User)
    bio = models.CharField(max_length=200, blank=True)
    profile_pic = models.ImageField(blank=True)
    phone_number = models.CharField(max_length=13)

    def __str__(self):
        return self.user.username
    

class Promo(models.Model):
    promo_code = models.CharField(max_length=10)

    def __str__(self):
        return self.promo_code

class TwilioMessage(models.Model):
    twilio_message = models.CharField(max_length=140)

tweet_messages/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User 
from phonenumber_field.modelfields import PhoneNumberField
from django import forms
from .models import TweetMessage, Promo, Profile
from . import views


class TweetMessageForm(forms.ModelForm):
    tweet_messages = forms.CharField(max_length=140)
    
    class Meta:
        model = TweetMessage
        fields = ('tweet_messages',)


class LoginForm(AuthenticationForm):
    pass

class PromoForm(forms.ModelForm):
    promo_code = forms.CharField(max_length=10)

    class Meta:
        model = Promo
        fields = ('promo_code',)


class ProfileForm(forms.ModelForm):
    phone_number = PhoneNumberField()
    bio = forms.CharField(max_length=200)

    class Meta:
        model = Profile
        fields = ('bio', 'phone_number')

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'password', 'password2',)


    def clean_password2(self):
        cd = self.cleaned_data

        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

tweet_messages/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import TweetMessage, Promo, Profile, TwilioMessage 
from .forms import TweetMessageForm, UserRegistrationForm, ProfileForm, PromoForm
from twilio.twiml import Response
from django_twilio.decorators import twilio_view


def index(request):

    tweets = TweetMessage.objects.all()

    context = {
        "tweets": tweets,
    
    }

    return render(request, "tweet_messages/index.html", context)

def users_list(request):

    user_list = User.objects.all()

    context = {
        "user_list": user_list,
    }

    return render(request, "tweet_messages/user_list.html", context)

def user_page(request, id):
    tweeter = get_object_or_404(User, pk=id)
    tweets = tweeter.tweetmessage_set.all()

    context = {
        "tweets": tweets,
        "tweeter": tweeter,
    }

    return render(request, "tweet_messages/user_page.html", context)

@login_required
def create_message(request):

    if request.method == "POST":
        form = TweetMessageForm(request.POST)
        if form.is_valid():
            new_message = form.save(commit=False)
            new_message.user_id = request.user.pk
            new_message.save()
            messages.success(request, 'Message Posted!')
            return redirect('tweet_messages:index')
    else:
        form=TweetMessageForm()

    context = {
        "form": form,
    }

    return render(request, "tweet_messages/create_message.html", context)


def register(request):
    if request.method== "POST":
        form = UserRegistrationForm(request.POST)
        form2 = ProfileForm(request.POST)
        form3 = PromoForm(request.POST)
        #testing out git
        if form.is_valid() and form2.is_valid() and form3.is_valid():
            codes = Promo.objects.all()
            user_code = form3.save(commit=False)
            for code in codes:
                if user_code.promo_code == code.promo_code: 
                    #if promo_codes match, then proceed to create new user
                    new_user = form.save(commit=False)
                    new_user.set_password(form.cleaned_data['password'])
                    
                    #save new user to database
                    new_user.save()
                    # print("new user: " + str(new_user))

                    #create instance of profile object, but do not save to database
                    user_profile = form2.save(commit=False)
                    # print ("type profile: " + type(user_profile))
                    # print ("new_user id: " + new_user.id)
                    user_profile.user_id = new_user.id
                    # import pdb; pdb.set_trace()
                    user_profile.save()
                    

            new_user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'],
                            )
            login(request, new_user)
            messages.success(request, "User Created!")

            return redirect('tweet_messages:user_list')
    else:
        form = UserRegistrationForm()
        form2 = ProfileForm()
        form3 = PromoForm()

    context = {
        "form": form,
        "form2": form2,
        "form3": form3,
    }
    return render(request, "tweet_messages/registration.html", context)

@twilio_view
def reply_to_sms_messages(request):
    r = Response()
    print(r)
    r.message('Hey Bootcampers, thanks for checking out my site!')
    # phone_number=(request.POST.get())
    # print(phone_number)

    TwilioMessage.objects.create(twilio_message=request.POST.get('Body', ''))
    return r

    # twilio_message = request.POST.get('Body', '')
    # twilio_message.save()
    

tweet_messages/templates/tweet_messages/_form_input.html
<div>
    {{field.label_tag}}
    {{field}}

    {% if field.errors %}
        <span class="help-block">
            {% for error in field.errors %}
                {{error}}
            {% endfor %}
        </span>
    {% endif %}
</div>

tweet_messages/templates/tweet_messages/base.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Social Messages
        {% endblock title %}
    </title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.light_green-light_blue.min.css" />

    <script src="https://use.fontawesome.com/a04d9e4c1c.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'tweet_messages/styles.css' %}" />
</head>
<body>
<!-- No header, and the drawer stays open on larger screens (fixed drawer). -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer">
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Social Messages</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="{% url 'tweet_messages:index' %}">Home</a>
    {% if request.user.is_authenticated %}
      <a class="mdl-navigation__link" href="{% url 'tweet_messages:user_list' %}">Users</a>
      <a class="mdl-navigation__link" href="{% url 'tweet_messages:create_message' %}">Create Post</a>
      <a class="mdl-navigation__link" href="{% url 'tweet_messages:user_page' request.user.pk %}">My Posts</a>
      <a class="mdl-navigation__link" href="{% url 'tweet_messages:logout' %}">Logout</a>
    {% else %}
      <a class="mdl-navigation__link" href="{% url 'tweet_messages:register' %}">Sign Up</a>
      <a class="mdl-navigation__link" href="{% url 'tweet_messages:login' %}">Login</a>
    {% endif %}
    </nav>
  </div>
<!-- End Menu -->
  <main class="mdl-layout__content">
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--1-col"></div>
        <div class="mdl-cell mdl-cell--10-col">
    <!-- Your content goes here -->
 
<!-- Main Content -->
    <!-- <div class="container">
     <div class="{% block content_classes %}main-content{% endblock content_classes %}"> -->
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}

        {% endblock %}
     <!--  </div>
    </div> -->

<!-- End Main Content -->
        </div>
        <div class="mdl-cell mdl-cell--1-col"></div>
    </div>
  </main>

<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer__left-section">
  </div>
  <div class="mdl-mini-footer__right-section">
    <ul class="mdl-mini-footer__link-list">
      <li><a href="">&copy; Gary | 2016</a></li>
    </ul>
  </div>
</footer>

</div> <!-- Closes Content Div -->

    <script defer src="https://code.getmdl.io/1.2.1/material.min.js"></script>
</body>
</html>

tweet_messages/templates/tweet_messages/create_message.html
{% extends 'tweet_messages/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}
  {{ block.super }} - Create a Message
{% endblock %}

{% block content_classes %}
    {{block.super}} index-content
{% endblock content_classes %}

{% block content %}

 
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--4-col"></div>
        <div class="mdl-cell mdl-cell--4-col">
            <form action="" method="POST">
            <div class="mdl-textfield mdl-js-textfield">
              {% csrf_token %}
              {{form|crispy}}
            </div>
            <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                Post
            </button>
            </form>
        </div>
    <div class="mdl-cell mdl-cell--4-col"></div>
</div>


{% endblock %}

tweet_messages/templates/tweet_messages/index.html
{% extends 'tweet_messages/base.html' %}
{% load staticfiles %}
{% load gravatar_tags %}

{% block title %}
  {{ block.super }} - Home
{% endblock %}

{% block content_classes %}
    {{block.super}} index-content
{% endblock content_classes %}

{% block content %}

 {% if request.user.is_authenticated %}
 <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="alert alert-info" role="alert">
      Hi {{request.user}}, let's chat.
      </div>
    </div>
  </div>
 {% endif %}

<div class="mdl-grid">
  <!-- <div class="mdl-cell"> -->
  
  {% for tweet in tweets %}
      <!-- start card -->
    <div class="mdl-cell mdl-cell--6-col">

       <div class="mdl-card mdl-shadow--4dp">
        <div class="mdl-card__media">
          <div class="profile-pic">
            <img src="{{ tweet.user|gravatar:100 }}" />
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <p>{{tweet.user}}</p>
            <small>{{tweet.date}}</small>
          </div>
        </div>
        <div class="mdl-card__supporting-text">
        {{tweet}}
        </div>
      </div>
    </div>

      <!-- end card -->
  {% endfor %}
  <!-- </div> -->
</div>

{% endblock %}

tweet_messages/templates/tweet_messages/login.html
{% extends "tweet_messages/base.html" %}

{% block content %}
<h2>Login</h2>

    {% if form.errors %}
    <div class="alert alert-danger">
        Incorrect username or password.
    </div>
    {% endif %}

<div class="mdl-grid">
   <div class="mdl-cell mdl-cell--4-col"></div>
   <div class="mdl-cell mdl-cell--4-col">
        <form action="{% url 'tweet_messages:login' %}" method="POST">
            {% csrf_token %}
            {% for field in form %}
                {%  include "tweet_messages/_form_input.html" %}
            {% endfor %}
            <!-- <input type="hidden" name="next" value="{{next}}"> -->
            <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
              Login
            </button>
        </form>
   </div>
   <div class="mdl-cell mdl-cell--4-col"></div>
</div>


{% endblock content %}

tweet_messages/templates/tweet_messages/registration.html
{% extends "tweet_messages/base.html" %}
{% load crispy_forms_tags %}

{%block content %}
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h2>
            Register
        </h2>
        <div id="registration_form">
        <form action="" method="POST">
            {% csrf_token %}

            {{ form|crispy }}
            {{ form2|crispy }}
            {{ form3|crispy }}
        <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
            Submit    
        </button>
        </form>
        </div>
    </div>
</div>


{% endblock content %}

tweet_messages/templates/tweet_messages/user_list.html
{% extends 'tweet_messages/base.html' %}
{% load staticfiles %}
{% load gravatar_tags %}

{% block title %}
  {{ block.super }} - Home
{% endblock %}

{% block content_classes %}
    {{block.super}} index-content
{% endblock content_classes %}

{% block content %}

<!-- List items with avatar and action -->
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--2-col"></div>
  <div class="mdl-cell mdl-cell--8-col">
    <h2>Users</h2>
    <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--4dp">
      <tbody>
      
      {% for x in user_list %}
        <tr>
          <td class="mdl-data-table__cell--non-numeric">
            <div class="profile-pic">
              <img src="{{ x|gravatar:100 }}" />
            </div>
          </td>
          <td class="mdl-data-table__cell--non-numeric">
            <h5>{{x.get_username}}</h5>
          </td>
          <td class="mdl-data-table__cell--non-numeric">
            <a href="{% url 'tweet_messages:user_page' x.pk %}">... see all {{x.get_username}} tweets</a>
          </td>
        </tr>
      {% endfor %}

      </tbody>
    </table>
  </div>
  <div class="mdl-cell mdl-cell--2-col"></div>
</div>

{% endblock %}

tweet_messages/templates/tweet_messages/user_page.html
{% extends 'tweet_messages/base.html' %}
{% load staticfiles %}

{% block title %}
  {{ block.super }} - Home
{% endblock %}

{% block content_classes %}
    {{block.super}} index-content
{% endblock content_classes %}

{% block content %}

<h2>{{tweeter}}</h2>

<div class="mdl-grid user-page">

{% for message in tweets %}
<!-- start card -->
  <div class="mdl-cell mdl-cell--4-col">

     <div class="mdl-card mdl-shadow--4dp">
      <div class="mdl-card__media">
        <div>
          <i class="fa fa-commenting" aria-hidden="true"></i> |
          <small>{{message.date}}</small>
        </div>
      </div>
      <div class="mdl-card__supporting-text">
      {{message}}
      </div>
    </div>
  </div>

<!-- end card -->
{% endfor %}

</div>

{% endblock %}